<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3.5 Missing data | Social Data Science with R</title>
  <meta name="description" content="This is basically course notes corresponding to a series of courses in educational data science, which are generally applicable to a wide range of social data science problems, taught through R." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="3.5 Missing data | Social Data Science with R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is basically course notes corresponding to a series of courses in educational data science, which are generally applicable to a wide range of social data science problems, taught through R." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3.5 Missing data | Social Data Science with R" />
  
  <meta name="twitter:description" content="This is basically course notes corresponding to a series of courses in educational data science, which are generally applicable to a wide range of social data science problems, taught through R." />
  

<meta name="author" content="Daniel Anderson" />
<meta name="author" content="Brendan Cullen" />
<meta name="author" content="Ouafaa Hmaddi" />


<meta name="date" content="2020-11-02" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="dealing-with-low-variance-predictors.html"/>
<link rel="next" href="transformations.html"/>
<script src="assets/header-attrs-2.5/header-attrs.js"></script>
<script src="assets/jquery-2.2.3/jquery.min.js"></script>
<link href="assets/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="assets/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="assets/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="assets/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="assets/anchor-sections-1.0/anchor-sections.js"></script>
<script src="assets/core-js-2.5.3/shim.min.js"></script>
<script src="assets/react-16.12.0/react.min.js"></script>
<script src="assets/react-16.12.0/react-dom.min.js"></script>
<script src="assets/reactwidget-1.0.0/react-tools.js"></script>
<script src="assets/htmlwidgets-1.5.2/htmlwidgets.js"></script>
<script src="assets/reactable-binding-0.2.3/reactable.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/3.5.16/iframeResizer.min.js" type="text/javascript"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preface</a></li>
<li class="chapter" data-level="2" data-path="welcome.html"><a href="welcome.html"><i class="fa fa-check"></i><b>2</b> Welcome</a></li>
<li class="chapter" data-level="3" data-path="feature-engineering.html"><a href="feature-engineering.html"><i class="fa fa-check"></i><b>3</b> Feature Engineering</a>
<ul>
<li class="chapter" data-level="3.1" data-path="basics-of-recipes.html"><a href="basics-of-recipes.html"><i class="fa fa-check"></i><b>3.1</b> Basics of {recipes}</a></li>
<li class="chapter" data-level="3.2" data-path="creating-a-recipe.html"><a href="creating-a-recipe.html"><i class="fa fa-check"></i><b>3.2</b> Creating a recipe</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="creating-a-recipe.html"><a href="creating-a-recipe.html#order-matters"><i class="fa fa-check"></i><b>3.2.1</b> Order matters</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="encoding-categorical-data.html"><a href="encoding-categorical-data.html"><i class="fa fa-check"></i><b>3.3</b> Encoding categorical data</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="encoding-categorical-data.html"><a href="encoding-categorical-data.html#transformations-beyond-dummy-coding"><i class="fa fa-check"></i><b>3.3.1</b> Transformations beyond dummy coding</a></li>
<li class="chapter" data-level="3.3.2" data-path="encoding-categorical-data.html"><a href="encoding-categorical-data.html#handling-new-levels"><i class="fa fa-check"></i><b>3.3.2</b> Handling new levels</a></li>
<li class="chapter" data-level="3.3.3" data-path="encoding-categorical-data.html"><a href="encoding-categorical-data.html#final-thoughts-on-encoding-categorical-data"><i class="fa fa-check"></i><b>3.3.3</b> Final thoughts on encoding categorical data</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="dealing-with-low-variance-predictors.html"><a href="dealing-with-low-variance-predictors.html"><i class="fa fa-check"></i><b>3.4</b> Dealing with low variance predictors</a></li>
<li class="chapter" data-level="3.5" data-path="missing-data.html"><a href="missing-data.html"><i class="fa fa-check"></i><b>3.5</b> Missing data</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="missing-data.html"><a href="missing-data.html#missing-data-via-recipes"><i class="fa fa-check"></i><b>3.5.1</b> Missing data via {recipes}</a></li>
<li class="chapter" data-level="3.5.2" data-path="missing-data.html"><a href="missing-data.html#a-few-words-of-caution"><i class="fa fa-check"></i><b>3.5.2</b> A few words of caution</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="transformations.html"><a href="transformations.html"><i class="fa fa-check"></i><b>3.6</b> Transformations</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="transformations.html"><a href="transformations.html#box-cox-and-similar-transformations"><i class="fa fa-check"></i><b>3.6.1</b> Box-Cox and similar transformations</a></li>
<li class="chapter" data-level="3.6.2" data-path="transformations.html"><a href="transformations.html#an-applied-example"><i class="fa fa-check"></i><b>3.6.2</b> An applied example</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="nonlinearity.html"><a href="nonlinearity.html"><i class="fa fa-check"></i><b>3.7</b> Nonlinearity</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="nonlinearity.html"><a href="nonlinearity.html#polynomial-transformations"><i class="fa fa-check"></i><b>3.7.1</b> Polynomial transformations</a></li>
<li class="chapter" data-level="3.7.2" data-path="nonlinearity.html"><a href="nonlinearity.html#splines"><i class="fa fa-check"></i><b>3.7.2</b> Splines</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="interactions.html"><a href="interactions.html"><i class="fa fa-check"></i><b>3.8</b> Interactions</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="interactions.html"><a href="interactions.html#creating-interactions-by-hand"><i class="fa fa-check"></i><b>3.8.1</b> Creating interactions “by hand”</a></li>
<li class="chapter" data-level="3.8.2" data-path="interactions.html"><a href="interactions.html#creating-interactions-with-recipes"><i class="fa fa-check"></i><b>3.8.2</b> Creating interactions with {recipes}</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="pca.html"><a href="pca.html"><i class="fa fa-check"></i><b>3.9</b> PCA</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="pca.html"><a href="pca.html#pca-with-recipes"><i class="fa fa-check"></i><b>3.9.1</b> PCA with {recipes}</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="wrapping-up.html"><a href="wrapping-up.html"><i class="fa fa-check"></i><b>3.10</b> Wrapping up</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Social Data Science with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="missing-data" class="section level2" number="3.5">
<h2><span class="header-section-number">3.5</span> Missing data</h2>
<p>If we look closely at our statewide testing data, we will see that there is a considerable amount of missingness. In fact, every row of the data frame has at least one value that is missing. The amount to which missing data impacts your work varies by field, but in most fields you’re likely to run into situations where you have to handle missing data in some way. The purpose of this section is to discuss a few approaches (as implemented through the {recipes} package) to handling missingness for predictive modeling purposes. Note that this is <strong>not</strong> a comprehensive discussion on the topic (for which, we recommend <a href="https://onlinelibrary.wiley.com/doi/book/10.1002/9781119013563">Little and Rubin (2002)</a>), but is instead an applied discussion of what you <em>can</em> do. As with many aspects of data analysis, generally, there is no single approach that will always work best, and it’s worth trying a few different approaches in your model development to see how different choices impact your model performance.</p>
<p>There are three basic ways of handling missing data:</p>
<ul>
<li><strong>Omit</strong> rows of the data frame that include missing values</li>
<li><strong>Encode</strong> or <strong>Impute</strong> the missing data</li>
<li><strong>Ignore</strong> the missing data and estimate from the available data</li>
</ul>
<p>The last option is not always feasible and will depend the modeling framework you’re working within. Some estimation procedures can also lend themselves to efficient handling of missing data (for example, imputation via the posterior distribution with Bayesian estimation). In this section, we’ll mostly focus on the first three. Additionally, we will only really be concerned with missingness on the predictor variables here, rather than the outcome. Generally, missing data on the predictors is a much more difficult problem than missingness on the outcome, because most models assume you have complete data across your predictors.</p>
<div id="missing-data-via-recipes" class="section level3" number="3.5.1">
<h3><span class="header-section-number">3.5.1</span> Missing data via {recipes}</h3>
<div id="omission" class="section level4" number="3.5.1.1">
<h4><span class="header-section-number">3.5.1.1</span> Omission</h4>
<p>We can <strong>omit</strong> missing data with <code>step_naomit</code>. This will remove any row that has any missing data. Let’s see how this impacts our data, working with our same recipe we finished up with in the <a href="creating-a-recipe.html#creating-a-recipe">Creating a recipe</a> section. I’ve placed the recipe here again so we don’t have to go back to remind ourselves what we did previously.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="missing-data.html#cb59-1"></a>rec &lt;-<span class="st"> </span><span class="kw">recipe</span>(score <span class="op">~</span><span class="st"> </span>., train) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb59-2"><a href="missing-data.html#cb59-2"></a><span class="st">  </span><span class="kw">update_role</span>(<span class="kw">contains</span>(<span class="st">&quot;id&quot;</span>), ncessch, <span class="dt">new_role =</span> <span class="st">&quot;id vars&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb59-3"><a href="missing-data.html#cb59-3"></a><span class="st">  </span><span class="kw">step_mutate</span>(<span class="dt">lang_cd =</span> <span class="kw">factor</span>(<span class="kw">ifelse</span>(<span class="kw">is.na</span>(lang_cd), <span class="st">&quot;E&quot;</span>, lang_cd)),</span>
<span id="cb59-4"><a href="missing-data.html#cb59-4"></a>              <span class="dt">tst_dt =</span> lubridate<span class="op">::</span><span class="kw">mdy_hms</span>(tst_dt)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb59-5"><a href="missing-data.html#cb59-5"></a><span class="st">  </span><span class="kw">step_zv</span>(<span class="kw">all_predictors</span>())</span>
<span id="cb59-6"><a href="missing-data.html#cb59-6"></a></span>
<span id="cb59-7"><a href="missing-data.html#cb59-7"></a>na_omit_data &lt;-<span class="st"> </span>rec <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb59-8"><a href="missing-data.html#cb59-8"></a><span class="st">  </span><span class="kw">step_naomit</span>(<span class="kw">all_predictors</span>()) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb59-9"><a href="missing-data.html#cb59-9"></a><span class="st">  </span><span class="kw">step_dummy</span>(<span class="kw">all_nominal</span>()) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb59-10"><a href="missing-data.html#cb59-10"></a><span class="st">  </span><span class="kw">prep</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb59-11"><a href="missing-data.html#cb59-11"></a><span class="st">  </span><span class="kw">bake</span>(<span class="dt">new_data =</span> <span class="ot">NULL</span>)</span>
<span id="cb59-12"><a href="missing-data.html#cb59-12"></a></span>
<span id="cb59-13"><a href="missing-data.html#cb59-13"></a><span class="kw">nrow</span>(na_omit_data)</span></code></pre></div>
<pre><code>## [1] 561</code></pre>
<p>As can be seen above, when we omit any row with missing data we end up with only 561 rows out of the original 2841 rows in the training data (or approximately 20% of the original data). This level of data omission is highly likely to introduce systematic biases into your model prediction. Generally, <code>step_naomit</code> should only be used when developing preliminary models, where you’re just trying to get code to run. When you get to the point where you’re actually trying to improve performance, you should consider alternative means</p>
</div>
<div id="encoding-and-simple-imputation" class="section level4" number="3.5.1.2">
<h4><span class="header-section-number">3.5.1.2</span> Encoding and simple imputation</h4>
<p>Encoding missing data is similar to imputation. In imputation, we replace the missing value with something we thing could have reasonably been the real value, if it were observed. When we encode missing data we are creating values that will be included in the modeling process. For example, with categorical variables, we could replace the missingess with a “missing” level, which would then get its own dummy code (if we were using dummy coding to encode the categorical variables).</p>
<p>I mentioned in the <a href="creating-a-recipe.html#creating-a-recipe">Creating a recipe</a> section that we were getting warnings but I was omitting them in the text. The reason is because some of these columns have missing data. If we want to avoid this warning, we have to add an additional step to our recipe to encode the missing data in the categorical variables. This step is called <code>step_unknown</code> and it replaces missing values with <code>"unknown"</code>. Let’s do this for all categorical variables, and omit any rows that are missing on numeric columns.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="missing-data.html#cb61-1"></a>na_encode_data &lt;-<span class="st"> </span>rec <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb61-2"><a href="missing-data.html#cb61-2"></a><span class="st">  </span><span class="kw">step_unknown</span>(<span class="kw">all_nominal</span>()) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb61-3"><a href="missing-data.html#cb61-3"></a><span class="st">  </span><span class="kw">step_naomit</span>(<span class="kw">all_predictors</span>()) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb61-4"><a href="missing-data.html#cb61-4"></a><span class="st">  </span><span class="kw">step_dummy</span>(<span class="kw">all_nominal</span>()) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb61-5"><a href="missing-data.html#cb61-5"></a><span class="st">  </span><span class="kw">prep</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb61-6"><a href="missing-data.html#cb61-6"></a><span class="st">  </span><span class="kw">bake</span>(<span class="dt">new_data =</span> <span class="ot">NULL</span>)</span>
<span id="cb61-7"><a href="missing-data.html#cb61-7"></a></span>
<span id="cb61-8"><a href="missing-data.html#cb61-8"></a><span class="kw">nrow</span>(na_encode_data)</span></code></pre></div>
<pre><code>## [1] 2784</code></pre>
<p>Notice in the above that when I call <code>step_naomit</code> I state that it should be applied to <code>all_predictors</code> because I’ve already encoded the nominal predictors in the previous step. This approach allows us to capture 98% of the original data. And as a bonus, we’ve removed ourselves of the warnings (note - we might also want to apply <code>step_novel</code> for any future data that had levels outside of our training data - see <a href="encoding-categorical-data.html#handling-new-levels">Handling new levels</a>).</p>
<p>Just a slight step up in complexity from omission of rows with missing data is to impute them with sample descriptive statistics, such as the mean or the median. Generally, I’ve found median imputation works better than mean imputation, but that could be related to the types of data I work with most frequently. Let’s switch datasets so we can see what’s happening more directly.</p>
<p>Let’s look at the <a href="https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/airquality.html">airquality</a> dataset, which ships with R.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="missing-data.html#cb63-1"></a><span class="kw">head</span>(airquality)</span></code></pre></div>
<pre><code>##   Ozone Solar.R Wind Temp Month Day
## 1    41     190  7.4   67     5   1
## 2    36     118  8.0   72     5   2
## 3    12     149 12.6   74     5   3
## 4    18     313 11.5   62     5   4
## 5    NA      NA 14.3   56     5   5
## 6    28      NA 14.9   66     5   6</code></pre>
<p>As we can see, <code>Solar.R</code> is missing for observations 5 and 6. Let’s compute the sample mean and median for this column.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="missing-data.html#cb65-1"></a><span class="kw">mean</span>(airquality<span class="op">$</span>Solar.R, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 185.9315</code></pre>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="missing-data.html#cb67-1"></a><span class="kw">median</span>(airquality<span class="op">$</span>Solar.R, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 205</code></pre>
<p>If we use mean or median imputation, we just replace the missing values with these sample statistics. Let’s do this with {recipes}, assuming we’ll be fitting a model where <code>Ozone</code> is the outcome, predicted by all other variables in the dataset.</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="missing-data.html#cb69-1"></a><span class="kw">recipe</span>(Ozone <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> airquality) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb69-2"><a href="missing-data.html#cb69-2"></a><span class="st">  </span><span class="kw">step_meanimpute</span>(<span class="kw">all_predictors</span>()) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb69-3"><a href="missing-data.html#cb69-3"></a><span class="st">  </span><span class="kw">prep</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb69-4"><a href="missing-data.html#cb69-4"></a><span class="st">  </span><span class="kw">bake</span>(<span class="dt">new_data =</span> <span class="ot">NULL</span>)</span></code></pre></div>
<pre><code>## # A tibble: 153 x 6
##    Solar.R  Wind  Temp Month   Day Ozone
##      &lt;int&gt; &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
##  1     190   7.4    67     5     1    41
##  2     118   8      72     5     2    36
##  3     149  12.6    74     5     3    12
##  4     313  11.5    62     5     4    18
##  5     186  14.3    56     5     5    NA
##  6     186  14.9    66     5     6    28
##  7     299   8.6    65     5     7    23
##  8      99  13.8    59     5     8    19
##  9      19  20.1    61     5     9     8
## 10     194   8.6    69     5    10    NA
## # … with 143 more rows</code></pre>
<p>As we can see, the value <span class="math inline">\(186\)</span> has been imputed for rows 5 and 6, which is the integer version of the sample mean (an integer was imputed because the column was already an integer, and not a double).</p>
<p>Let’s try the same thing with median imputation</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="missing-data.html#cb71-1"></a><span class="kw">recipe</span>(Ozone <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> airquality) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb71-2"><a href="missing-data.html#cb71-2"></a><span class="st">  </span><span class="kw">step_medianimpute</span>(<span class="kw">all_predictors</span>()) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb71-3"><a href="missing-data.html#cb71-3"></a><span class="st">  </span><span class="kw">prep</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb71-4"><a href="missing-data.html#cb71-4"></a><span class="st">  </span><span class="kw">bake</span>(<span class="dt">new_data =</span> <span class="ot">NULL</span>)</span></code></pre></div>
<pre><code>## # A tibble: 153 x 6
##    Solar.R  Wind  Temp Month   Day Ozone
##      &lt;int&gt; &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
##  1     190   7.4    67     5     1    41
##  2     118   8      72     5     2    36
##  3     149  12.6    74     5     3    12
##  4     313  11.5    62     5     4    18
##  5     205  14.3    56     5     5    NA
##  6     205  14.9    66     5     6    28
##  7     299   8.6    65     5     7    23
##  8      99  13.8    59     5     8    19
##  9      19  20.1    61     5     9     8
## 10     194   8.6    69     5    10    NA
## # … with 143 more rows</code></pre>
<p>And as we would expect, the missingness has now been replaced with values of <span class="math inline">\(205\)</span>.</p>
<p>Sometimes you have time series data, or there is a date variable in the dataset that accounts for a meaningful proportion of the variance. In these cases, you might consider <code>step_rollimpute</code>, which provides a conditional median imputation based on time, and you can set the size of the window from which to calculate the median. In still other cases it may make sense to just impute with the lowest observed value (i.e., assume a very small amount of the predictor), which can be accomplished with <code>step_lowerimpute</code>.</p>
<p>These simple imputation techniques are fine to use when developing models. However, it’s an area that may be worth returning to as you start to refine your model to see if you can improve performance.</p>
</div>
<div id="modeling-the-missingness" class="section level4" number="3.5.1.3">
<h4><span class="header-section-number">3.5.1.3</span> Modeling the missingness</h4>
<p>Another alternative for imputation is to fit a statistical model with the column you want to impute modeled as the outcome, with all other columns (minus the actual outcome) predicting it. We then use that model for the imputation. Let’s first consider a linear regression model. We’ll fit the same model we specified in our recipe, using the airquality data.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="missing-data.html#cb73-1"></a>m &lt;-<span class="st"> </span><span class="kw">lm</span>(Solar.R <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> airquality[ ,<span class="op">-</span><span class="dv">1</span>])</span>
<span id="cb73-2"><a href="missing-data.html#cb73-2"></a><span class="kw">summary</span>(m)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Solar.R ~ ., data = airquality[, -1])
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -182.945  -67.348    5.295   73.781  170.068 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -14.5960    84.4424  -0.173 0.863016    
## Wind          2.1661     2.2633   0.957 0.340171    
## Temp          3.7023     0.9276   3.991 0.000105 ***
## Month       -13.2640     5.4525  -2.433 0.016242 *  
## Day          -1.0631     0.8125  -1.308 0.192875    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 85.14 on 141 degrees of freedom
##   (7 observations deleted due to missingness)
## Multiple R-squared:  0.131,  Adjusted R-squared:  0.1063 
## F-statistic: 5.313 on 4 and 141 DF,  p-value: 0.0005145</code></pre>
<p>Notice that I’ve dropped the first column here, which is <code>Ozone</code>, our actual outcome. The model above has been fit using the equivalent of <code>step_naomit</code>, otherwise known as <em>listwise deletion</em>, where any row with any missing data is removed.</p>
<p>We can now use the coefficients from this model to impute the missing values in <code>Solar.R</code>. For example, row 6 in the dataset had a missing value on <code>Solar.R</code> and following values for all other variables</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="missing-data.html#cb75-1"></a>row6 &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">Wind =</span> <span class="fl">14.9</span>, </span>
<span id="cb75-2"><a href="missing-data.html#cb75-2"></a>                   <span class="dt">Temp =</span> <span class="dv">66</span>, </span>
<span id="cb75-3"><a href="missing-data.html#cb75-3"></a>                   <span class="dt">Month =</span> <span class="dv">5</span>, </span>
<span id="cb75-4"><a href="missing-data.html#cb75-4"></a>                   <span class="dt">Day =</span> <span class="dv">6</span>)</span></code></pre></div>
<p>Using our model, we would predict the following score for this missing value</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="missing-data.html#cb76-1"></a><span class="kw">predict</span>(m, <span class="dt">newdata =</span> row6)</span></code></pre></div>
<pre><code>##        1 
## 189.3325</code></pre>
<p>Let’s try this using {recipes}.</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="missing-data.html#cb78-1"></a><span class="kw">recipe</span>(Ozone <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> airquality) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb78-2"><a href="missing-data.html#cb78-2"></a><span class="st">  </span><span class="kw">step_impute_linear</span>(<span class="kw">all_predictors</span>()) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb78-3"><a href="missing-data.html#cb78-3"></a><span class="st">  </span><span class="kw">prep</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb78-4"><a href="missing-data.html#cb78-4"></a><span class="st">  </span><span class="kw">bake</span>(<span class="dt">new_data =</span> <span class="ot">NULL</span>)</span></code></pre></div>
<pre><code>## # A tibble: 153 x 6
##    Solar.R  Wind  Temp Month   Day Ozone
##      &lt;int&gt; &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
##  1     190   7.4    67     5     1    41
##  2     118   8      72     5     2    36
##  3     149  12.6    74     5     3    12
##  4     313  11.5    62     5     4    18
##  5     152  14.3    56     5     5    NA
##  6     189  14.9    66     5     6    28
##  7     299   8.6    65     5     7    23
##  8      99  13.8    59     5     8    19
##  9      19  20.1    61     5     9     8
## 10     194   8.6    69     5    10    NA
## # … with 143 more rows</code></pre>
<p>And we see two important things here. First, row 6 for <code>Solar.R</code> is indeed as we expected it to be (albeit, in integer form). Second, the imputed values for rows 5 and 6 are now <em>different</em>, which is the first time we’ve seen this via imputation.</p>
<p>The same basic approach can be used for essentially any statistical model. The {recipes} package has currently implemented linear imputation (as above), <span class="math inline">\(k\)</span>-nearest neighbor imputation, and bagged imputation (via bagged trees). Let’s see how rows 5 and 6 differ with these approaches.</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="missing-data.html#cb80-1"></a><span class="kw">recipe</span>(Ozone <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> airquality) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb80-2"><a href="missing-data.html#cb80-2"></a><span class="st">  </span><span class="kw">step_knnimpute</span>(<span class="kw">all_predictors</span>()) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb80-3"><a href="missing-data.html#cb80-3"></a><span class="st">  </span><span class="kw">prep</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb80-4"><a href="missing-data.html#cb80-4"></a><span class="st">  </span><span class="kw">bake</span>(<span class="dt">new_data =</span> <span class="ot">NULL</span>)</span></code></pre></div>
<pre><code>## # A tibble: 153 x 6
##    Solar.R  Wind  Temp Month   Day Ozone
##      &lt;int&gt; &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
##  1     190   7.4    67     5     1    41
##  2     118   8      72     5     2    36
##  3     149  12.6    74     5     3    12
##  4     313  11.5    62     5     4    18
##  5     159  14.3    56     5     5    NA
##  6     220  14.9    66     5     6    28
##  7     299   8.6    65     5     7    23
##  8      99  13.8    59     5     8    19
##  9      19  20.1    61     5     9     8
## 10     194   8.6    69     5    10    NA
## # … with 143 more rows</code></pre>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="missing-data.html#cb82-1"></a><span class="kw">recipe</span>(Ozone <span class="op">~</span><span class="st"> </span>., <span class="dt">data =</span> airquality) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb82-2"><a href="missing-data.html#cb82-2"></a><span class="st">  </span><span class="kw">step_bagimpute</span>(<span class="kw">all_predictors</span>()) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb82-3"><a href="missing-data.html#cb82-3"></a><span class="st">  </span><span class="kw">prep</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb82-4"><a href="missing-data.html#cb82-4"></a><span class="st">  </span><span class="kw">bake</span>(<span class="dt">new_data =</span> <span class="ot">NULL</span>)</span></code></pre></div>
<pre><code>## # A tibble: 153 x 6
##    Solar.R  Wind  Temp Month   Day Ozone
##      &lt;int&gt; &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
##  1     190   7.4    67     5     1    41
##  2     118   8      72     5     2    36
##  3     149  12.6    74     5     3    12
##  4     313  11.5    62     5     4    18
##  5     129  14.3    56     5     5    NA
##  6     244  14.9    66     5     6    28
##  7     299   8.6    65     5     7    23
##  8      99  13.8    59     5     8    19
##  9      19  20.1    61     5     9     8
## 10     194   8.6    69     5    10    NA
## # … with 143 more rows</code></pre>
<p>These models are quite a bit more flexible than linear regression, and can potentially overfit. You can, however, control some of the parameters to the models through additional arguments (e.g., <span class="math inline">\(k\)</span> for <span class="math inline">\(knn\)</span>, which defaults to 5). The benefit of these models is that they may provide better estimates of what the imputed value <em>would</em> have been, were it not missing, which may then improve model performance. The downside is that they are quite a bit more computationally intensive. Generally, you use recipes within processes like <span class="math inline">\(k\)</span>-fold cross-validation, with the recipe being applied to each fold. In this case, a computationally expensive approach may significantly bog down hyperparameter tuning.</p>
</div>
</div>
<div id="a-few-words-of-caution" class="section level3" number="3.5.2">
<h3><span class="header-section-number">3.5.2</span> A few words of caution</h3>
<p>Missing data is a highly complex topic. This section was meant to provide a basic overview of some of the options you can choose from when building a predictive model. <strong>None</strong> of these approaches, however, will “fix” data that are missing not at random (MNAR). Unfortunately, it is usually impossible to know if your data are MNAR, and we therefore assume that that are MAR, or missing at random conditional on the observed data. For example, if boys were more likely to have missing data on the outcome than girls, we could account for this by including a gender variable in the model, and the resulting data would be MAR.</p>
<p>If you have significant missing data, this section is surely incomplete. We recommended <a href="https://onlinelibrary.wiley.com/doi/book/10.1002/9781119013563">Little and Rubin (2002)</a> previously, and there are a number of other good resources, including <a href="http://www.feat.engineering/handling-missing-data.html">a chapter</a> in Kuhn and Johnson (2019).</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="dealing-with-low-variance-predictors.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="transformations.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="assets/gitbook-2.6.7/js/app.min.js"></script>
<script src="assets/gitbook-2.6.7/js/lunr.js"></script>
<script src="assets/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="assets/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="assets/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
},
"toolbar": {
"position": "static"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
